name: bmi_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_sign_in: ^7.2.0
  pinput: ^6.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.11.4

flutter:
  uses-material-design: true
  assets:
    - assets/colors/
    - assets/png/
    - assets/svg/
    - assets/fonts/
    - .env

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 700
          style: normal

    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
          style: normal

flutter_gen:
  output: lib/gen

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors
